### ISSUE TITLE
Rimionship Button reagiert verzögert

### ISSUE THREAD

**Issue by Drake2177** [pardeike/Rimionship#11]
Nach dem drücken des roten Rimionship Buttons (ich war mit der Seite verbunden) dauert es lange bis der Ladebildschirm kommt.  Dadurch wirkt es, als wäre der Button kaputt.  Ist das bei anderen auch so? (Der Ladebildschirm danach geht nun gaaaaanz schnell vorüber und ich bin quasi sofort im Spiel!)

**Comment by pardeike** [comment]
Das liegt daran das wir die aktuelle Spieledatei (Save game) vom Server laden. Und ja, da muß noch ein Ladedialog rein. Good catch!

**Comment by pardeike** [comment]
Gefixt in 585699ec1c50d97c3cc15fc484c41b10a3489ed2
