### ISSUE TITLE
Pfeil oben rechts im Menü sollte auf den eigenen Spieler zeigen

### ISSUE THREAD

**Issue by theronhh** [pardeike/Rimionship#13]
- Oben rechts ist ein kleiner weißer Pfeil im ausgeklappten Menü, dieser soll auf den eigenen Username zeigen.
- Aktuell tut er das nicht.
- Der Fehler lässt sich reproduzieren. 
- Der aktuelle Spieler ist Bambus_Bjoern_ (oben)

<img src="https://user-images.githubusercontent.com/70449436/185678021-ad97dd96-ae31-4014-9667-b2fedc61ab6e.png"/>
<img src="https://user-images.githubusercontent.com/70449436/185677789-562a2180-0e82-42c7-81d0-d55c649b5d4e.png"/>

**Comment by pardeike** [comment]
Außerdem haben wir bei total=3 Spielern und man ist auf Platz 3 nur die Anzeige von 2+3 (3 in der Mitte) aber nicht wie erwartet 1+2+3 und Pfeil auf die 3.
