### ISSUE TITLE
Blutgott Balken verschwindet nach erstem Opfer

### ISSUE THREAD

**Issue by Schemfil** [pardeike/Rimionship#14]
**Describe the bug**
Wird ein Kolonist geopfert (egal ob per Selbst-Opferung oder Opfer eines anderen) verschwindet der Fortschrittsbalken des Blutgottes, selbst wenn nach der Opferung noch deutlich mehr Kolonisten als der Threshold vorhanden sind.

Reproduzierbar mit der aktuellen Version der Mod bei drei verschiedenen Testern (MrPaetBLN, Ethawulf, Schemfil)

**To Reproduce**
- Große Zahl an Kolonisten im DEV Mode spawnen (Koloniegrößen getestet: 7, 20)
- Einen Kolonisten opfern (Selbst-Opferung oder Fremd-Opferung)

**Expected behavior**
Solange nach der Opferung mehr als 5 Kolonisten noch am Leben sind bleibt dfer Blutgott-Balken bestehen, wird zurückgesetzt und lädt sich erneut auf.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/86972764/185746605-54e35506-397e-4e09-89e4-2d701eedae9e.png)

**Comment by pardeike** [comment]
Das ist der Cooldown. Ich designe das ganze um:
- Pentagramhintergrund hat fünf "Füllzustände" von leer bis 5 Einheiten voll
- Direkt vor dem Opferspruch erhöht sich der Füllstand +1
- Nach dem Opfern (im Cooldown) wird ein (vielleicht schwarzer) Balken der herunter geht angezeigt, der normale Balken bleibt voll
- Wenn Cooldown zueende verschwindet dieser Balken und der Opferspruch beginnt.

**Comment by pardeike** [comment]
Fixed
