### ISSUE TITLE
Komischer Zeichensatz auf Deutscher Sprache mit Dev Mod "on"

### ISSUE THREAD

**Issue by theronhh** [pardeike/Rimionship#16]
- Sprache Deutsch, Dev Mod on
- Beim pawn Generator am Anfang ist am Knopf "Filter" ein komischer Font. Beim anklicken auch innerhalb des Untermenüs.
- In der Original Sprache tritt der Fehler nicht auf.
- Tritt auch bei ingame Fenstern teilweise auf siehe letztem Bild

![Filter_Button_Start_pawn_generation](https://user-images.githubusercontent.com/70449436/185746906-ce391cb7-4c6b-4394-9193-4881de397556.png)

![Filter_Button_Start_pawn_generation](https://user-images.githubusercontent.com/70449436/185746915-bbd7cf63-a523-49bc-8515-f793c5c76739.png)

![font_german_txt](https://user-images.githubusercontent.com/70449436/185748431-9cd8ea9c-eef7-400e-927f-14ef715ce170.jpg)

**Comment by pardeike** [comment]
Ah, kein Bug. Das ist so wenn man Dev Mode an hat.
