### ISSUE TITLE
Bei deutscher Spielsprache sind englische Wörter seltsam dargestellt

### ISSUE THREAD

**Issue by Schemfil** [pardeike/Rimionship#17]
**Describe the bug**
Wird die Spielsprache auf "Deutsch" gestellt, werden Buchstaben in englischen Texten im Game auf eine seltsame Art dargestellt (siehe Screenshots unten). Die Buchstaben sind noch irgendwie ähnlich zu ihren "Originalen", aber scheinen aus einem anderen Alphabet zu stammen.
Betroffen sind Wörter, die aus Mods stammen und nur auf Englisch verfügbar sind (keine deutsche Übersetzung vorhanden) wie z.B. bei der RimHUD "Schedule", "Outfit", "aged", "and", "days", "in stable health", usw.

Stellt man die Spielsprache auf "Englisch", sieht die Schrift normal aus.
Wird ein deutscher Spielstand mit nachträglich deaktivierter RS Mod erneut geladen werden alle Texte auch mit deutscher Einstellung wieder im normalen Zeichensatz dargestellt.

Trat bei zwei von zwei Spielern reproduzierbar auf.

**Expected behavior**
Sowohl in englischer als auch deutscher Einstellung keine Beeinträchtigung der Schriften.

**Screenshots**
Deutsch mit RS Mod aktiviert:
![grafik](https://user-images.githubusercontent.com/86972764/185766213-38e89980-6956-44c8-88f0-2f6a6bde1042.png)

Deutsch mit nachträglich deaktiverter RS Mod:
![grafik](https://user-images.githubusercontent.com/86972764/185766217-00260938-0294-4918-bce9-46957c928d27.png)

**Comment by pardeike** [comment]
Das ist so im Dev-Modus. Alle nicht übersetzten Begriffe werden so dargestellt damit man sieht was nicht übersetzt wird.
