### ISSUE TITLE
Required Features

### ISSUE THREAD

**Issue by bartimaeusnek** [pardeike/Rimionship#18]
- [ ] verifying final version of blood god events
- [x] final text for DO NOT SHARE dialog for training session
- [x] final text for WHAT IS BLOOD GOD dialog for first time blood god event
- [x] final versions of blood god sound files
- [ ] connect blood god sounds to events *[possible?]*

**Comment by pardeike** [comment]
**connect blood god sounds to events** hat ein logisches Problem: Wenn man den Sound vor einem spezifischen Event abspielt und dieser Event fehlschlägt (d.h. nicht ausführbar ist) und der Code automatisch einen anderen Event versucht auszuführen dann würden Sounds mehrfach abgespielt werden. Momentan wird ein zufälliger Sound gespielt und dann ein Event (mit Retry) und dadurch geht's
