### ISSUE TITLE
Kein Effekt von "Rising Reduction Per Colonist" 

### ISSUE THREAD

**Issue by Schemfil** [pardeike/Rimionship#19]
**Describe the bug**
Der Parameter "Rising Reduction Per Colonist" scheint keinen Effekt zu haben.
Eine Änderung an der Basisdauer sorgt direkt für eine Änderung des aktuellen Blutgott-Meters. Eine deutliche Erhöhung der Reduktion pro Kolonist tut das nicht.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/86972764/189199124-351df9e4-c633-41a0-8a48-3dba6cef1f28.png)

**Comment by pardeike** [comment]
Good catch!
