### ISSUE TITLE
Detailbeschreibung des Opferplatzes

### ISSUE THREAD

**Issue by Schemfil** [pardeike/Rimionship#20]
Der Opferplatz soll eine detaillierte Beschreibung bekommen die als Nachschlagewerk für den Spieler dienen soll.

Der Text wird von Schemfil beigestellt.

**Comment by Schemfil** [comment]
An diesem Opferplatz kannst du einen Kolonisten opfern um den Blutgott zu beruhigen.
Diese Handlung wird deine übrigen Kolonisten erfreuen. Je länger du dem Blutgott vorher widerstanden hast, desto mehr werden sie erleichtert sein.

Nach einiger Zeit wird er allerdings erneut nach einem Opfer verlangen. Also wähle den Zeitpunkt zu dem du opferst mit Bedacht.

Ignorierst du den Blutgott zu lange wird er anfangen, deine Kolonie zu bestrafen.
Zu Beginn sind diese Strafen noch recht harmlos. Verärgerst du ihn aber weiter, werden auch die Strafen immer schlimmer ausfallen.

Um einen Kolonisten zu opfern, wähle zunächst den Pawn, der das Opfer durchführensoll aus. Klicke dann mit der rechten Maustaste auf den Pawn, der geopfert werden soll und wähle die entsprechende Option im Kontext-Menü.
Ein Kolonist kann sich auch selbst opfern.

Das Opfer-Ritual wird von deinen Kolonisten anschließend besucht, allerdings mit sehr geringer Priorität. Stehen andere Dinge an wie z.B. Essen oder Schlafen, werden deine Kolonisten eher diesen nachgehen bevor sie an der Opferung teilnehmen.
Dies gilt auch für alle Zuschauer, die sich um das Ritual herum schaaren werden.
Du kannst ihnen jederzeit andere Aufgaben geben, oder sie draften, sollte die Situation das gerade erfordern.

Ein e bereits begonnene Opferung kannst du hier am Opferplatz wider abbrechen.

**Comment by pardeike** [comment]
Fixed mit folgenden Änderungen:

An diesem Opferplatz kannst man Kolonisten opfern um den Blutgott zu beruhigen. Diese Handlung wird die übrigen Kolonisten erfreuen. Je länger dem Blutgott vorher widerstanden wird, desto mehr werden die Kolonisten erleichtert sein.\n\nNach einiger Zeit wird der Blutgott allerdings erneut nach einem Opfer verlangen, also wähle den Zeitpunkt an dem geopfert wird mit Bedacht.\n\nIgnoriert man den Blutgott zu lange wird er anfangen, die Kolonie zu bestrafen. Zu Beginn sind diese Strafen noch recht harmlos. Wenn man ihn jedoch ignoriert, werden die Strafen nur noch schlimmer.\n\nUm einen Kolonisten zu opfern, wählt man zunächst den Kolonisten aus, der das Opfer durchführen soll. Dann klickt man mit der rechten Maustaste auf den Kolonisten, der geopfert werden soll und wählt im Kontext-Menü das entsprechende Kommando aus. Ein Kolonist kann sich auch selbst opfern.\n\nDer Opferplatz wird anschließend von deinen Kolonisten besucht, allerdings mit geringer Priorität. Stehen andere Dinge an wie z.B. Essen oder Schlafen, werden deine Kolonisten eher diesen nachgehen bevor sie an der Opferung teilnehmen. Dies gilt auch für alle Zuschauer, die sich um das Ritual herum scharen werden. Man kann ihnen jederzeit andere Aufgaben geben, oder sie in den Kampfmodus versetzen, sollte die Situation das gerade erfordern.\n\nEine bereits begonnene Opferung kann man hier am Opferplatz wieder abbrechen.

At this sacrification spot you can sacrifice colonists to calm down the blood god. This action will please the rest of the colonists. The longer the Blood God is resisted beforehand, the more relieved the colonists will be.\n\nAfter a while, however, the Blood God will ask for a sacrifice again, so choose the timing of the sacrifice wisely.\n\nIgnore the Blood God too long and he will start punishing the colony. At first, these penalties are quite harmless. However, ignoring it will only make the penalties worse.\n\nTo sacrifice a colonist, first select the colonist that should perform the sacrifice. Then click with the right mouse button on the colonist who is to be sacrificed and select the corresponding command in the context menu. A colonist can also sacrifice themselves.\n\nThe sacrification spot will then be visited by your colonists, but with low priority. If there are other things to do, such as eating or sleeping, your colonists will be more likely to do those things before participating in the sacrifice. This also applies to all spectators who are attendending the ritual. You can give colonists other tasks at any time, or put them into combat mode if the situation requires it.\n\nAn already started sacrifice can be canceled here at the sacrification spot.
