### ISSUE TITLE
Button "Turnier Beenden"

### ISSUE THREAD

**Issue by Schemfil** [pardeike/Rimionship#22]
Um den Koloniewert final abzugeben und danach das Spiel weiterspielen zu können soll im selben Panel wie die Auswahl der Hauptkarte ein Button in Rot eingebaut werden.

Button-Text: "Spielstand einreichen"

Sicherheitsfrage
"Turnier vorzeitig beenden und Punktestand abgeben?"
[Ja] [Nein]

**Comment by Schemfil** [comment]
Sicherheitsfrage Detailtext unter dem oben angegebenen Titel:

Mit Klick auf "Ja" wird der Koloniewert endgültig für das Turnier abgegeben. Das Spiel kann danach weiter gespielt werden, allerdings findet keine weitere Wertung in der Haupt- oder den Nebenquests statt.
Diese Entscheidung ist unwiderruflich und auch nicht durch einen Neustart zurück zu ziehen.

Willst du sicher deine Endwertung der Rimionship jetzt einreichen?

**Comment by pardeike** [comment]
Text, Button und Dialog fertig
Kommunikation zum Server fehlt noch
