### ISSUE TITLE
Blutgott Event wird nicht getriggert

### ISSUE THREAD

**Issue by Schemfil** [pardeike/Rimionship#23]
**Describe the bug**
Der Balken vom Blutgott füllt sich, aber es triggert das erste Event nicht sobald er voll ist. Er bleibt einfach weiterhin voll ohne einen Effekt auszulösen.
Trat auf im Training-Modus bei drei Testern.
Devmode war aktiv.

**To Reproduce**
Kolonist opfern
Blutgott Balken voll laufen lassen

**Expected behavior**
Tier 1 Event wird getriggert

**Screenshots**
![grafik](https://user-images.githubusercontent.com/86972764/189755840-4147c322-e6e1-443a-b1bf-773a3b502768.png)

**Comment by Schemfil** [comment]
Payzee berichtet, dass schätzungsweise 15 Minuten nachdem der Balken voll gefüllt war eine Reaktion des Blutgotts kam

**Comment by Schemfil** [comment]
Testfall bei mir

Rising Intervall: 48h
Rising Reduction per Colonist: 12h
Minimum: 4h

Reduktion muss anhand meiner Kolonisten 24h betragen

Der Blutgott Balken ist auch nach 24h voll
Das Event wird aber erst nach genau 48h ausgelöst.

Es scheint also so, als ob der Balken die Reduktion berücksichtigen würde, der Trigger für das Event aber nur den Basis "Rising Intervall" verwendet

**Comment by pardeike** [comment]
Ah, gute Observation. Da hab ich vergessen eine Stelle zu ändern als wir die Reduktion gefixt haben. Check ich morgen.
