### ISSUE TITLE
Forschung funktioniert nicht

### ISSUE THREAD

**Issue by KleinesJulchen** [pardeike/Rimionship#3]
Forschung ist ausgewählt, Kolonisten gehen zum Forschungstisch und forschen, es werden jedoch keine Forschungspunkte generiert. 

Probiert bei "Pemmican" und "Batterie". Bei beiden das gleiche Problem.

**Comment by pardeike** [comment]
Immer gerne ein Save-Game hochladen und erklären wie das Problem reproduziert werden kann. Danke

**Comment by KleinesJulchen** [comment]
Save hochgeladen im DC per PN (03.08. 09:15)

**Comment by pardeike** [comment]
Problem gefunden: Der Schwierigkeitsgrad wird nicht initialisiert und damit ist der Research-Faktor 0. Werd mal schauen wie ich das fixe.

**Comment by pardeike** [comment]
Update: in einer neuen Map scheint es zu funktionieren. D.h. die Startmap die du benutzt hast scheint irgendwie defekt zu sein. Kannst du mal ein neues Rimionship-Spiel anfangen und sehen ob Research immer noch nicht klappt?

**Comment by KleinesJulchen** [comment]
Erneut getestet, funktioniert ohne Probleme. Issue kann geschlossen werden.
