### ISSUE TITLE
Opferplatz Duplikat nach Umzug

### ISSUE THREAD

**Issue by Schemfil** [pardeike/Rimionship#33]
**Describe the bug**
Nach einem Umzug kommt e sunter bestimmten Bedingungen zu einem Duplikat des Opferplatzes auf der Map. Dieses Duplikat ist nicht auswählbar und rein optisch vorhanden.
Es kann nicht abgerissen werden und verhindert nicht den Bau eines neuen Opferplatzes.

**To Reproduce**
1. Opferplatz bauen
2. Karawane zu einem anderen Feld schicken
3. Alte Kolonie noch während des Umzugs aufgeben
4. Neue Kolonie gründen
5. Opferplatz-Duplikat erscheint auf der neuen Map

**Expected behavior**
Der Opferplatz bleibt einzigartig - auch optisch :D

**Screenshots**
![grafik](https://user-images.githubusercontent.com/86972764/192160051-fd4f3a1e-091f-4724-8b2b-629762de606e.png)

**Comment by pardeike** [comment]
Mist, den kenn ich. Hab ich vergessen als Issue anzulegen. Naja, nun gibt es eine Issue :-)

**Comment by pardeike** [comment]
fixed
