### ISSUE TITLE
Laden eines ungültigen Savegames scheint dessen Koloniewert an Server zu übertragen

### ISSUE THREAD

**Issue by Schemfil** [pardeike/Rimionship#34]
Scheinbar verursacht der Versuch ein Savegame zu laden eine Übertragung von dessen Koloniewert an den Server.
Bis zum Ende des Ladevorgangs soll daher die Kommunikation mit dem Server unterbunden werden um ungültige "Sprünge" in den Werten zu verhindern

**Comment by pardeike** [comment]
Gefixt mit neuem Load/Save-Dialog
