### ISSUE TITLE
BG Mood-Debuff wechselt in der Stimmungsansicht ständig den Platz mit einem anderen

### ISSUE THREAD

**Issue by Schemfil** [pardeike/Rimionship#39]
![grafik](https://user-images.githubusercontent.com/86972764/192378000-1df32acf-0d12-43f4-942a-833dad412480.png)

Beide -2 Werte "zittern" ständig hin und her (wechseln ihre Positionen) - auch bei Spielpause

**Comment by pardeike** [comment]
fixed
