### ISSUE TITLE
Opferung funktioniert nicht korrekt 

### ISSUE THREAD

**Issue by KleinesJulchen** [pardeike/Rimionship#4]
Nach 3 (oder 4? bin nicht sicher) Zyklen habe ich versucht einen Pawn zu opfern. 
1. Versuch: Einen Pawn ausgewählt -  "ofere mich selber für den Bluttgott" über den Opferspot ausgewählt - nix passiert 
2. Anschließend wollte ich über den Ritualplatz oder direkt über die Pawnkontrolle mit dem Ritualplatz interagieren. Es ging gar nichts mehr (es kam keine Auswahlmöglichkeit beim Ritualplatz) 
3. Ich habe die Aktion auf dem Ritualplatz entfernt (das finde ich noch nicht ganz eindeutig - die Unterscheidung zwischen Aktion abbrechen und Platz entfernen erkennt man noch nicht so gut) und erneut versucht eine Aktion zu triggern. Ging leider auch nicht. 
4. Ich habe den Spot gelöscht und neu gesetzt. Dann konnte ich wieder mit einem Pawn "opfere mich selber " auswählen, es ist aber wieder nichts passiert. 
5. Ein erneutes löschen wäre erst "nach 22h" (wahrscheinlich nach 24h default?) möglich 

Opferung war nicht erfolgreich *g

**Comment by pardeike** [comment]
Bitte ein Save-Game hochladen damit ich es nachvollziehen kann.

**Comment by KleinesJulchen** [comment]
Save hochgeladen im DC per PN (03.08. 09:15)

**Comment by pardeike** [comment]
Die Mechanik wie Kolonisten auf das Operritual reagieren wurde komplett umgeschrieben außerdem hab ich ein paar Bugs mit dem Enfernen/Abbrechen des Spotes/Rituals bereinigt. Bitte also noch mal neu testen.

**Comment by KleinesJulchen** [comment]
Erneut getestet, Opferung funktioniert nun. Issue kann geschlossen werden.

**Comment by pardeike** [comment]
Wir haben leider nun ein Problem das Drake mir via Discord erzählt hat: wenn ein Kolonist auf dem Weg zum Opferplatz durchdreht dann bleibt die gesamte Logik stecken.

Das liegt daran das ich nach dem ursprünglichen Feedback viel aggressiver bin im Jobverteilen damit die Kolonisten nix anderes machen. Wenn dann aber eine solche Art von Unterbrechung kommt (oder man versucht die Kolonisten zu draften) das gibt es Probleme. 

Diese Issue erinnert mich daran das noch besser hi designen.

**Comment by pardeike** [comment]
Fixed
