### ISSUE TITLE
Setting Änderung nach Beginn betrifft das aktuelle Game nicht

### ISSUE THREAD

**Issue by Schemfil** [pardeike/Rimionship#40]
Wenn nach Spielstart die Settings geändert werden hat das auf das aktuelle Spiel des Teilnehmers keine Auswirkungen.
Auch beim Laden des Spiels werden die neuen Settings nicht angewendet.
Nur bei einem Neustart eines Runs sind die Settings dann aktiv.

**Comment by pardeike** [comment]
Muß mit der neuen Version noch mal gecheckt werden. Nicht vergessen die custom env auszumachen!

**Comment by pardeike** [comment]
War ein Serverproblem (Aktualsierenknopf nicht vergessen)
