### ISSUE TITLE
Setting Änderung wird nur übernommen wenn RW offen ist

### ISSUE THREAD

**Issue by Schemfil** [pardeike/Rimionship#41]
Werden die Settings geändert, betrifft das nur Spielstände, die aktuell geöffnet sind.
Lädt man einen Save von früher, läuft dieser weiterhin mit den damaligen Einstellungen, selbst wenn eine Kommunikation zum Server besteht.
Erst durch erneutes Aktivieren der Settings während dieser Save geladen ist, wird er upgedated

Erwartet:
Geladene Saves holen sich immer die aktuelle Konfiguration vom Server ab

**Comment by pardeike** [comment]
Bitte mit master testen. Logging an und man sieht die settings wenn sie vom Server kommen

**Comment by Schemfil** [comment]
Funktion an mehreren Savegames bestätigt
