### ISSUE TITLE
Anpassung der erlaubten Mods [Pinned]

### ISSUE THREAD

**Issue by Schemfil** [pardeike/Rimionship#7]
Liste der erlaubten Mods anpassen

[-] Entfernen
- RPG Style Inventory

[+] Hinzufügen
    Name     | Package ID    |  ID
+ Mod List | pyrce.modlist | 1545126946
+ RimHUD | Jaxe.RimHUD | 1508850027
+ RandomPlus | mastertea.RandomPlus | 1434137894

**Comment by pardeike** [comment]
War mein Bauchgefühl doch richtig. Danke fürs nachschauen.

**Comment by pardeike** [comment]
Updated

**Comment by Drake2177** [comment]
Modlist verursacht noch immer eine Fehlermeldung: 
![Screenshot 2022-09-17 205323](https://user-images.githubusercontent.com/110996197/190872347-524b2d50-fee1-485a-9d38-8d792e58afdd.jpg)

**Comment by pardeike** [comment]
„Modlist“ ist mittlerweile kein erlaubter Mod mehr. Deswegen ist dein Screenshot genau richtig.

**Comment by Drake2177** [comment]
dann muss er nur noch aus der aktuellen modliste raus, hab sie erst heute neu geladen

**Comment by pardeike** [comment]
Diese Modliste enhält sowieso aus technischen Gründen nicht exakt die Mods die erlaubt sind. Z.b ColonyWealth oder das Fehlen der Rimionship Mod.
