### ISSUE TITLE
kein Bug - eher Einstellungssache zum Blutgottevent

### ISSUE THREAD

**Issue by KleinesJulchen** [pardeike/Rimionship#9]
Szenario: Man kommt das 1. Mal auf 6 Kolonisten: 
Das Blutgottevent wird getriggert, man opfert einen Kolonisten (ist somit wieder bei 5 Kolonisten)
Rekrutiert man dann wieder den 6. Kolonisten wird sofort wieder das Event getriggert. Wachstum ist so nicht möglich. 

Link zum Savegame: https://www.filemail.com/d/ujimsqiienjpbiy

**Comment by pardeike** [comment]
Ich denke das das das normale Verhalten ist. Wenn man mehr als die erlaubten Kolonisten hat dann geht das Blutgott-Meter hoch. Hab gerade getestet und als ich wieder auf 6 hochgegangen bin ging das steigen der Anzeige wieder los. 

Vielleicht hat dich verwirrt das die Werte für alle Parameter momentan sehr niedrig gehalten sind, d.h. die Anzeige geht sehr schnell hoch sobald man zu viele Kolonisten hat.

Mit den neuen Einstellungen ist das Ansteigen abhängig von der Anzahl der zu vielen Kolonisten (mehr = schneller).

**Comment by pardeike** [comment]
Sollte gefixt sein
